kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ics-csi-controller
  namespace: kube-system
spec:
  serviceName: ics-csi-controller
  replicas: 1
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: ics-csi-controller
  template:
    metadata:
      labels:
        app: ics-csi-controller
        role: ics-csi
    spec:
      serviceAccountName: ics-csi-controller
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - operator: "Exists"
          key: node-role.kubernetes.io/master
          effect: NoSchedule
      hostNetwork: true
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.1.1
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--timeout=300s"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: ics-csi-controller
          image: ics-csi-driver:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /var/lib/csi/sockets/pluginproxy/csi.incloudsphere.inspur.com"]
          args:
            - "--v=5"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: X_CSI_MODE
              value: "controller"
            - name: ICSPHERE_CSI_CONFIG
              value: "/etc/ics/icsphere-csi.conf"
          volumeMounts:
            - mountPath: /etc/ics
              name: ics-config-volume
              readOnly: true
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 3
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:v1.1.0
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.2.2
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--timeout=300s"
            - "--csi-address=$(ADDRESS)"
            - "--feature-gates=Topology=true"
            - "--strict-topology"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: ics-csi-syncer
          image: ics-csi-syncer:latest
          args:
            - "--v=5"
          imagePullPolicy: IfNotPresent
          env:
            - name: FULL_SYNC_INTERVAL_MINUTES
              value: "3"
            - name: ICSPHERE_CSI_CONFIG
              value: "/etc/ics/icsphere-csi.conf"
          volumeMounts:
            - mountPath: /etc/ics
              name: ics-config-volume
              readOnly: true
      volumes:
        - name: ics-config-volume
          secret:
            secretName: ics-config-secret
        - name: socket-dir
          hostPath:
            path: /var/lib/csi/sockets/pluginproxy/csi.incloudsphere.inspur.com
            type: DirectoryOrCreate
---
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: csi.incloudsphere.inspur.com
spec:
  attachRequired: true
  podInfoOnMount: true
