# Copyright 2020 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
pause_image: mcr.microsoft.com/oss/kubernetes/pause:1.4.0
containerd_additional_settings: ""

prepull: false
prepull_images:
  2019:
    - mcr.microsoft.com/windows/servercore:ltsc2019
    - mcr.microsoft.com/windows/nanoserver:1809
    - mcr.microsoft.com/oss/kubernetes/pause:1.4.0
  2004:
    - mcr.microsoft.com/windows/servercore:2004
    - mcr.microsoft.com/windows/nanoserver:2004
    - mcr.microsoft.com/oss/kubernetes/pause:1.4.0

additional_prepull_images_list: "{{ additional_prepull_images.split(',') if (additional_prepull_images is defined) and (additional_prepull_images|length > 0) else [] }}"
